---
title: "Clean Movebank reference data within the GULLIVER project"
author: "Sanne Govaert"
date: "`r Sys.Date()`"
output:
  html_document
---


```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

Load libraries:

```{r}
library(tidyverse)
library(here)
```

Set user-defined values:

```{r}
project_id <- "LBBG_SCHIERMONNIKOOG"
end_date <- "2020-12-31 24:00:00"
```

## Read reference data

```{r}
path <- here::here("data", "processed", project_id, "movebank_ref_data.csv")
ref_data <- readr::read_csv(path)
```

## Process/filter reference data

```{r}
ref_data <-
  ref_data |>
  dplyr::mutate(
    `animal-comments` = NA_character_,
    `animal-life-stage` = dplyr::if_else(
      grepl("chick|juvenile", `animal-comments`, ignore.case = TRUE) |
      grepl("chick|juvenile", `deployment-comments`, ignore.case = TRUE),
      "juvenile",
      `animal-life-stage`
    ),
    `deployment-comments` = NA_character_,
    `deployment-end-type` = NA_character_,
    `manipulation-type` = dplyr::if_else(
      grepl("heart rate implant", `animal-comments`, ignore.case = TRUE),
      "manipulated-other",
      `manipulation-type`
    )
  ) |>
  dplyr::filter(`animal-life-stage` == "adult") |>
  dplyr::filter(`deploy-on-timestamp` <= as.POSIXct(end_date, tz = "UTC"))
```

## Write reference data

```{r}
readr::write_csv(
  ref_data,
  here::here("data", "processed", project_id, "movebank_ref_data.csv"),
  na = ""
)
```
