---
title: "Download individuals metadata from UvA-BiTS"
author: "Peter Desmet"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
    number_sections: true
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

Load libraries:

```{r}
library(tidyverse)
library(DBI)
library(here)
library(glue)
```

## Connect to UvA-BiTS database

Get connection settings from `config.yml` (not included in this repo) and connect to database:

```{r connect_to_uvabits}
uvabits <- config::get("uvabits")
con = dbConnect(
  RPostgres::Postgres(),
  host = uvabits$server,
  port = uvabits$port,
  user = uvabits$username,
  password = uvabits$password,
  dbname = uvabits$database
)

# The alternative is getting the connection defined in odbc.ini:
# con <- dbConnect(odbc::odbc(), "uvabits")
```

## Get metadata from all projects

Get data on individuals and their associated track sessions from all bird tracking projects you have access to.

Query data:

```{r}
sql <- read_file(here("sql", "individuals.sql"))
metadata <- dbGetQuery(con, sql)
```

Save to csv:

```{r}
write_csv(metadata, path = here("data", "interim", "individuals.csv"), na = "")
```

