---
title: "Download UvA-BiTS tracking data as Movebank GPS data"
author: "Peter Desmet"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
    number_sections: true
---

# Setup

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

Load libraries:

```{r}
library(tidyverse)
library(here)
library(RPostgreSQL)
library(glue)
```

# Connect to UvA-BiTS database

Get credentials from config file (not included in this repo) and create a database connection:

```{r connect_to_uvabits}
uvabits <- config::get("uvabits")
con = dbConnect(
  dbDriver("PostgreSQL"),
  user = uvabits$username,
  password = uvabits$password,
  host = uvabits$server,
  port = uvabits$port,
  dbname = uvabits$database
)
```

# Download tracking data as Movebank GPS data

...

Set values:

```{r}
project <- "MH_WATERLAND"
device_info_serial <- 586
```

Query data:

```{r}
sql <- glue_sql(read_file(here("sql", "movebank_gps_data.sql")), .con = con)
movebank_gps_data <- dbGetQuery(con, sql)
```

Save to CSV:

```{r}
write_csv(movebank_gps_data, path = here("data", "processed", project, paste0("movebank_gps_data_", device_info_serial, ".csv")), na = "")
```
